### ISSUE TITLE
[ramuda] Settings file generation - json format

### ISSUE THREAD

**Issue by olysyuk** [glomex/gcdt#295]
Currently it's possible to specify settings by adding 

```
{
    "ramuda": {
       "settings": "<settings string goes here>"
    }
}
```

Please add options to generate settings file in multiple formats (conf and json).
Supporting dictionary to define settings file content will be much more efficient than relying on concatenated string.

**Comment by markfink** [comment]
we should have that for tenkai as well!

**Comment by markfink** [comment]
fixed with the new release 0.1.418. anybody wants to try it out?
@olysyuk , @webratz

**Comment by olysyuk** [comment]
The issue is still present.

{code}
{
    "ramuda": {
		"lambda": {
			"description": "Lambda function for playlist-autoselection-service",
            "events": {}, 
            "handlerFile": "lambda.js",
            "runtime": "nodejs6.10",
            "handlerFunction": "lambda.handler",
            "memorySize": "128", 
            "name": "mes-video-access"
		},
		"settings": {
			"env": "lookup:stack:stack:output"
		}
	}
}
{code}

Expected result. settings.json file is added to bundle
Actual result. Error: ERROR: ramuda gcdt-bundler: must be string or read-only buffer, not dict

Looks like only doccumentation was updated on commits, not the code itself.

**Comment by markfink** [comment]
just submitted a PR for a fix: https://github.com/glomex/gcdt/pull/388
